name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          pip install javascript
          # -----------------------
          python crpy.py
          # -----------------------
          git config --global user.name 'v'
          git config --global user.email 'v@users.noreply.github.com'
          git add .
          git commit -am "Automated report"
          git push
