name: CI
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - name: rrrrrrrr
        run: |
          pip install javascript pandas
          # -----------------------
          python crpy.py > crp.txt
          # -----------------------
          git config --global user.name 'v'
          git config --global user.email 'v@users.noreply.github.com'
          git add .
          git commit -am "Automated report"
          git push
